name: lib
description: A new Flutter module project.
version: 1.0.0+1
homepage: null
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_size_text: any
  cached_network_image: any
  cupertino_icons: ^1.0.2
  flex_color_scheme: any
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
